name: opening_hour_display_widget
description: "A Flutter plugin to display opening hours of a business, with a customizable design."
version: 0.0.3
homepage: https://github.com/Hery34/opening_hour_display_widget

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/

 
